// Сервис альбома: гости загружают фото с праздника.
// Знает только адрес API приглашений. Удаление приглашения узнаёт из события invitation.deleted.
// Фото хранятся на диске (data/files) или, если задан BLOB_READ_WRITE_TOKEN, в Vercel Blob — тогда в photos.file полный адрес файла.
const fs = require('fs');
const path = require('path');
const { env, TYPES, json, readRaw, readJson, parseMultipart, sendFile, inside, notFound, api, HttpError, createService } = require('../lib/http');
const { openDb } = require('../lib/db');
const blob = require('./blob');

const INVITATIONS_API = env('INVITATIONS_API');
const DATA = env('DATA_DIR', path.join(__dirname, '..', 'data'));
const FILES = path.join(DATA, 'files');
const BLOB = blob.enabled();
// у Vercel тело запроса не больше 4,5 МБ — фото уменьшает страница альбома перед загрузкой
const MAX_PHOTO = BLOB ? 4.3e6 : 15e6;
const TOO_BIG = BLOB ? 'Фото больше 4,3 МБ — уменьшите его' : 'Фото больше 15 МБ';
// на Vercel диск контейнера не постоянный: без Blob фото пропали бы — загрузку отключаем (503), остальное работает
const NO_STORAGE = process.env.VERCEL === '1' && !BLOB;
const NO_STORAGE_LOG = '[album] VERCEL=1, но BLOB_READ_WRITE_TOKEN не задан: диск не постоянный, загрузка фото отключена (503). Подключите Vercel Blob.';
if (NO_STORAGE) console.error(NO_STORAGE_LOG);
// защита от злоупотреблений: загрузок с одного IP за 10 минут и фото в одном альбоме
const IP_MAX = Number(env('UPLOADS_PER_IP')) || 30, ALBUM_MAX = Number(env('MAX_PHOTOS')) || 300;
const IP_WINDOW = 10 * 60e3, HITS_TTL = 60 * 60e3;

// число и порядок миграций не менять — только дописывать новые в конец
const db = openDb({
  file: path.join(DATA, 'album.db'), name: 'album', migrations: [
    {
      sqlite: `CREATE TABLE photos (
     id INTEGER PRIMARY KEY AUTOINCREMENT,
     invitation_id TEXT NOT NULL,
     file TEXT NOT NULL,
     name TEXT,
     created_at TEXT NOT NULL
   );
   CREATE INDEX photos_invitation ON photos (invitation_id);`,
      pg: `CREATE TABLE photos (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     invitation_id TEXT NOT NULL,
     file TEXT NOT NULL,
     name TEXT,
     created_at TEXT NOT NULL
   );
   CREATE INDEX album_photos_invitation ON photos (invitation_id);`,
    },
    // попытки загрузки по IP (at — мс), старше часа удаляются по ходу загрузок
    {
      sqlite: `CREATE TABLE album_hits (key TEXT NOT NULL, at INTEGER NOT NULL);
   CREATE INDEX album_hits_key ON album_hits (key, at);`,
      pg: `CREATE TABLE album_hits (key TEXT NOT NULL, at BIGINT NOT NULL);
   CREATE INDEX album_hits_key ON album_hits (key, at);`,
    },
  ],
});

const known = new Map();
async function requireInvitation(id, { published = false } = {}) {
  const hit = known.get(id);
  let x;
  // помним только найденное (30 с) и только для чтения: загрузку проверяем всегда —
  // только что одобренное должно сразу принимать фото, удалённое (событие пришло в другой экземпляр) — уже нет
  if (hit && !published && Date.now() - hit.at < 30e3) x = hit.value;
  else {
    x = null;
    try { x = await api(INVITATIONS_API, `/api/invitations/${encodeURIComponent(id)}`); }
    catch (e) { if (e.status !== 404) throw new HttpError(503, 'Сервис приглашений недоступен'); }
    if (x) { if (known.size > 5000) known.clear(); known.set(id, { at: Date.now(), value: x }); }
  }
  if (!x) throw new HttpError(404, 'Приглашение не найдено');
  if (published && x.status !== 'published') throw new HttpError(409, 'Приглашение ещё не опубликовано');
  return x;
}

// запрос к сервису приглашений от имени вызывающего: пересылаем Cookie/Authorization, права проверяет он
async function asCaller(req, pathname) {
  if (!INVITATIONS_API) throw new HttpError(503, 'Адрес сервиса не задан');
  const headers = {};
  if (req.headers.authorization) headers.authorization = req.headers.authorization;
  if (req.headers.cookie) headers.cookie = req.headers.cookie;
  const res = await fetch(INVITATIONS_API.replace(/\/+$/, '') + pathname, { headers, signal: AbortSignal.timeout(8000) })
    .catch(() => { throw new HttpError(503, 'Сервис приглашений недоступен'); });
  const data = await res.json().catch(() => null);
  if (res.status >= 500) throw new HttpError(503, 'Сервис приглашений недоступен');
  if (!res.ok) throw new HttpError(res.status, (data && data.error) || 'Нет доступа');
  return data;
}
// удалить фото может только хозяин приглашения (или админ)
const requireOwner = (req, id) => asCaller(req, `/api/invitations/${encodeURIComponent(id)}/owner`);

// IP клиента: левый адрес x-forwarded-for (ставит шлюз или Vercel), иначе адрес сокета
function clientIp(req) {
  const fwd = String(req.headers['x-forwarded-for'] || '').split(',')[0].trim();
  return (fwd || req.socket.remoteAddress || '').replace(/^::ffff:/, '').slice(0, 64);
}
// лимиты до чтения тела (одним запросом к базе): сначала записываем попытку, потом считаем —
// так попытка учтена до проверки и пачка параллельных запросов проскочит разве что на единицы.
// Старые попытки чистим не чаще раза в 10 минут (на каждом экземпляре).
let swept = 0;
async function checkLimits(req, id) {
  const now = Date.now(), key = 'ip:' + clientIp(req), list = [];
  if (now - swept > IP_WINDOW) { swept = now; list.push(['DELETE FROM album_hits WHERE at < ?', now - HITS_TTL]); }
  list.push(['INSERT INTO album_hits (key, at) VALUES (?, ?)', key, now],
    ['SELECT COUNT(*) AS n FROM album_hits WHERE key = ? AND at > ?', key, now - IP_WINDOW],
    ['SELECT COUNT(*) AS n FROM photos WHERE invitation_id = ?', id]);
  const [hits, photos] = (await db.batch(list)).slice(-2).map(r => Number(r.rows[0].n));
  if (hits > IP_MAX) throw new HttpError(429, 'Слишком много загрузок, попробуйте позже');
  if (photos >= ALBUM_MAX) throw new HttpError(409, `В альбоме уже ${ALBUM_MAX} фото — больше загрузить нельзя`);
}
// имя гостя: без NUL и прочих управляющих символов (переводы строк и табуляция — в пробел) и смены направления текста, до 80 символов
const cleanName = s => [...s.replace(/[\p{Cc}\p{Bidi_Control}]/gu, c => (/\s/.test(c) ? ' ' : '')).replace(/\s+/g, ' ').trim()].slice(0, 80).join('').trim();
// fs.promises.rm: синхронный rmSync в Node 24 на Windows молча не удаляет пути с не-ASCII символами
const removeDir = dir => fs.promises.rm(dir, { recursive: true, force: true });

const photoUrl = (id, file) => (blob.isBlobUrl(file) ? file : `/files/albums/${id}/${file}`);
// удалить файлы фото (строки из базы уже удалены); сбой хранилища не мешает ответу
async function removeFiles(id, files) {
  await blob.del(files).catch(e => console.error('[album] не удалось удалить из Blob:', e.message));
  for (const f of files) if (!blob.isBlobUrl(f)) await fs.promises.rm(path.join(FILES, id, f), { force: true });
}

// тип файла по первым байтам — принимаем только картинки
function imageExt(buf) {
  if (buf[0] === 0xff && buf[1] === 0xd8) return '.jpg';
  if (buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return '.png';
  if (buf.toString('latin1', 0, 4) === 'GIF8') return '.gif';
  if (buf.toString('latin1', 0, 4) === 'RIFF' && buf.toString('latin1', 8, 12) === 'WEBP') return '.webp';
  if (buf.toString('latin1', 4, 8) === 'ftyp') return /heic|heix|mif1/.test(buf.toString('latin1', 8, 12)) ? '.heic' : '.avif';
  return null;
}

createService('album', [
  ['GET', '/api/i/:id/album', async (req, res, { params }) => {
    await requireInvitation(params.id);
    const rows = await db.all('SELECT * FROM photos WHERE invitation_id = ? ORDER BY id DESC', params.id);
    json(res, 200, rows.map(p => ({ id: p.id, name: p.name, created_at: p.created_at, url: photoUrl(params.id, p.file) })));
  }],

  ['POST', '/api/i/:id/album', async (req, res, { params }) => {
    if (NO_STORAGE) { console.error(NO_STORAGE_LOG); throw new HttpError(503, 'Загрузка фото временно недоступна'); }
    if (Number(req.headers['content-length']) > MAX_PHOTO + 1e5) throw new HttpError(413, TOO_BIG);
    await checkLimits(req, params.id);
    await requireInvitation(params.id, { published: true });
    const raw = await readRaw(req, MAX_PHOTO + 1e5).catch(e => { throw e.status === 413 ? new HttpError(413, TOO_BIG) : e; });
    const parts = parseMultipart(raw, req.headers['content-type']);
    const file = parts.find(p => p.name === 'file' && p.filename);
    if (!file || !file.body.length) throw new HttpError(400, 'Выберите фото');
    if (file.body.length > MAX_PHOTO) throw new HttpError(413, TOO_BIG);
    const ext = imageExt(file.body);
    if (!ext) throw new HttpError(400, 'Это не картинка');
    const name = cleanName(((parts.find(p => p.name === 'name') || {}).body || Buffer.alloc(0)).toString('utf8'));
    let stored;
    if (BLOB) {
      try { stored = await blob.put(`albums/${params.id}/photo${ext}`, file.body, TYPES[ext]); }
      catch (e) { console.error('[album]', e.message); throw new HttpError(503, 'Хранилище фото недоступно, попробуйте позже'); }
    } else {
      stored = `${Date.now()}${Math.floor(Math.random() * 1000)}${ext}`;
      fs.mkdirSync(path.join(FILES, params.id), { recursive: true });
      fs.writeFileSync(path.join(FILES, params.id, stored), file.body);
    }
    // запись — только если альбом всё ещё не полон (пока читали тело, могли загрузить другие)
    let added;
    try {
      ({ rows: added } = await db.run(`INSERT INTO photos (invitation_id, file, name, created_at)
        SELECT ?, ?, ?, ? WHERE (SELECT COUNT(*) FROM photos WHERE invitation_id = ?) < ? RETURNING id`,
      params.id, stored, name, new Date().toISOString(), params.id, ALBUM_MAX));
    } catch (e) { await removeFiles(params.id, [stored]).catch(() => {}); throw e; }
    if (!added.length) {
      await removeFiles(params.id, [stored]).catch(() => {});
      throw new HttpError(409, `В альбоме уже ${ALBUM_MAX} фото — больше загрузить нельзя`);
    }
    json(res, 200, { ok: true });
  }],

  ['DELETE', '/api/i/:id/album/:photo', async (req, res, { params }) => {
    // id фото — только цифры: иначе Postgres ответил бы ошибкой на BIGINT
    if (!/^\d{1,15}$/.test(params.photo)) throw new HttpError(404, 'Фото не найдено');
    await requireOwner(req, params.id);
    const { rows } = await db.run('DELETE FROM photos WHERE id = ? AND invitation_id = ? RETURNING file', Number(params.photo), params.id);
    if (!rows.length) throw new HttpError(404, 'Фото не найдено');
    await removeFiles(params.id, rows.map(r => r.file));
    json(res, 200, { ok: true });
  }],

  ['GET', '/files/albums/*', (req, res, { params }) => {
    const f = inside(FILES, params.rest);
    return f ? sendFile(req, res, f) : notFound(res);
  }],

  // счётчики для «Моих приглашений»: ?ids=a,b,c (без ids — все) — только приглашения вошедшего, без входа 401.
  // Чьи приглашения — спрашиваем сервис приглашений с cookie вызывающего, как при удалении фото
  ['GET', '/api/album/stats', async (req, res, { url }) => {
    const list = await asCaller(req, '/api/invitations');
    const mine = new Set((Array.isArray(list) ? list : []).map(x => x.id));
    const asked = url.searchParams.get('ids');
    const ids = (asked == null ? [...mine] : [...new Set(asked.split(','))].filter(id => mine.has(id))).slice(0, 500);
    const out = Object.fromEntries(ids.map(id => [id, { photos: 0 }]));
    if (ids.length) {
      const rows = await db.all(`SELECT invitation_id, COUNT(*) AS n FROM photos WHERE invitation_id IN (${ids.map(() => '?').join(',')}) GROUP BY invitation_id`, ...ids);
      for (const r of rows) out[r.invitation_id].photos = Number(r.n);
    }
    json(res, 200, out);
  }],

  // события других сервисов
  ['POST', '/events', async (req, res) => {
    const e = await readJson(req);
    if (e.type === 'invitation.deleted' && e.id && /^[a-z0-9]+$/.test(e.id)) {
      known.delete(e.id);
      const { rows } = await db.run('DELETE FROM photos WHERE invitation_id = ? RETURNING file', e.id);
      await blob.del(rows.map(r => r.file)).catch(err => console.error('[album] не удалось удалить из Blob:', err.message));
      await removeDir(path.join(FILES, e.id));
    }
    json(res, 200, { ok: true });
  }],
]);
