// Сервис гостей: ответы на анкету («приду / с парой / не приду») и пожелания.
// Знает только адрес API приглашений: есть ли приглашение, опубликовано ли, кто владелец.
// Удаление приглашения узнаёт из события invitation.deleted (POST /events).
// База — SQLite-файл или Postgres (DATABASE_URL), см. lib/db.js; всё обращение к базе асинхронное.
const path = require('path');
const { env, json, send, readJson, api, HttpError, createService } = require('../lib/http');
const { openDb } = require('../lib/db');
const { classify, summary } = require('./rsvp');

const INVITATIONS_API = env('INVITATIONS_API');
const AUTH_API = env('AUTH_API');

// миграции применяются по номеру: порядок и число записей не менять, только дописывать в конец
const db = openDb({ name: 'guests', file: env('DB_FILE', path.join(__dirname, '..', 'data', 'guests.db')), migrations: [
  { sqlite: `CREATE TABLE answers (
     id INTEGER PRIMARY KEY AUTOINCREMENT,
     invitation_id TEXT NOT NULL,
     form_id TEXT,
     action TEXT,
     action_text TEXT,
     fields TEXT NOT NULL,
     created_at TEXT NOT NULL
   );
   CREATE INDEX answers_invitation ON answers (invitation_id);
   CREATE TABLE wishes (
     id INTEGER PRIMARY KEY AUTOINCREMENT,
     invitation_id TEXT NOT NULL,
     name TEXT NOT NULL,
     message TEXT NOT NULL,
     created_at TEXT NOT NULL
   );
   CREATE INDEX wishes_invitation ON wishes (invitation_id);`,
    // в общей базе Postgres имена индексов — с префиксом сервиса
    pg: `CREATE TABLE answers (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     invitation_id TEXT NOT NULL,
     form_id TEXT,
     action TEXT,
     action_text TEXT,
     fields TEXT NOT NULL,
     created_at TEXT NOT NULL
   );
   CREATE INDEX guests_answers_invitation ON answers (invitation_id);
   CREATE TABLE wishes (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     invitation_id TEXT NOT NULL,
     name TEXT NOT NULL,
     message TEXT NOT NULL,
     created_at TEXT NOT NULL
   );
   CREATE INDEX guests_wishes_invitation ON wishes (invitation_id);` },
  // guest_key — случайный id устройства гостя: повторный ответ заменяет прежний
  { sqlite: `ALTER TABLE answers ADD COLUMN guest_key TEXT;
   CREATE INDEX answers_guest ON answers (invitation_id, form_id, guest_key);`,
    pg: `ALTER TABLE answers ADD COLUMN guest_key TEXT;
   CREATE INDEX guests_answers_guest ON answers (invitation_id, form_id, guest_key);` },
  `ALTER TABLE answers ADD COLUMN status TEXT NOT NULL DEFAULT 'unknown';`,
  // журнал записей гостей для ограничения частоты: в памяти нельзя — на Vercel экземпляров несколько и они засыпают
  { sqlite: `CREATE TABLE guests_hits (key TEXT NOT NULL, at INTEGER NOT NULL);
   CREATE INDEX guests_hits_key ON guests_hits (key, at);`,
    pg: `CREATE TABLE guests_hits (key TEXT NOT NULL, at BIGINT NOT NULL);
   CREATE INDEX guests_hits_key ON guests_hits (key, at);` },
  // курсор журнала удалений invitations
  `CREATE TABLE guests_sync (name TEXT PRIMARY KEY, value TEXT NOT NULL);`,
] });

// текст гостя: без NUL и прочих управляющих C0, кроме \n и \t (Postgres не принимает NUL),
// и без одиночных суррогатов (в том числе от обрезки посреди эмодзи)
const clip = (s, n) => String(s ?? '').toWellFormed().replace(/[\0-\x08\x0b-\x1f]/g, '').trim().slice(0, n).replace(/[\ud800-\udbff]$/, '');

// приглашение (кеш 30 с): гости могут отвечать только на опубликованные.
// fresh — мимо кеша (для записи: снятое с публикации или удалённое не должно ещё 30 с принимать ответы)
const known = new Map();
async function invitation(id, { fresh = false } = {}) {
  const hit = known.get(id);
  // помним только найденное (30 с): только что одобренное должно сразу принимать ответы
  if (!fresh && hit && Date.now() - hit.at < 30e3) return hit.value;
  let value = null;
  try { value = await api(INVITATIONS_API, `/api/invitations/${encodeURIComponent(id)}`); }
  catch (e) { if (e.status !== 404) throw new HttpError(503, 'Сервис приглашений недоступен'); }
  if (value) { if (known.size > 5000) known.clear(); known.set(id, { at: Date.now(), value }); }
  else known.delete(id);
  return value;
}
async function requirePublished(id) {
  const x = await invitation(id, { fresh: true });
  if (!x) throw new HttpError(404, 'Приглашение не найдено');
  if (x.status !== 'published') throw new HttpError(409, 'Приглашение ещё не опубликовано');
  return x;
}
// запрос к сервису приглашений от имени вызывающего: его Cookie и Authorization пересылаются как есть
async function asCaller(req, pathname) {
  if (!INVITATIONS_API) throw new HttpError(503, 'Сервис приглашений недоступен');
  const headers = {};
  if (req.headers.authorization) headers.authorization = req.headers.authorization;
  if (req.headers.cookie) headers.cookie = req.headers.cookie;
  const res = await fetch(INVITATIONS_API.replace(/\/+$/, '') + pathname, { headers, signal: AbortSignal.timeout(8000) })
    .catch(() => { throw new HttpError(503, 'Сервис приглашений недоступен'); });
  const data = await res.json().catch(() => null);
  if (res.status >= 500) throw new HttpError(503, 'Сервис приглашений недоступен');
  if (!res.ok) throw new HttpError(res.status, (data && data.error) || 'Нет доступа');
  return data;
}
// ответы видит только владелец (или админ): права по cookie проверяет сервис приглашений
const requireOwner = (req, id) => asCaller(req, `/api/invitations/${encodeURIComponent(id)}/owner`);

// адрес гостя: первый в x-forwarded-for (его ставит шлюз или Vercel), иначе — сокет
const clientIp = req => (String(req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.socket.remoteAddress || '').slice(0, 64);
// не больше max записей одного вида (ответы, пожелания) за 10 минут с одного адреса.
// Счётчик — в базе (guests_hits): проверка и запись одной командой, отклонённое не записывается.
// Записи старше часа чистим не чаще раза в 10 минут
let swept = 0;
async function limit(req, kind, max) {
  const key = kind + ':' + clientIp(req), now = Date.now();
  const sweep = now - swept > 600e3 ? (swept = now, [['DELETE FROM guests_hits WHERE at < ?', now - 3600e3]]) : [];
  const out = await db.batch([...sweep, [`INSERT INTO guests_hits (key, at) SELECT ?, CAST(? AS BIGINT)
    WHERE (SELECT COUNT(*) FROM guests_hits WHERE key = ? AND at > ?) < ? RETURNING at`, key, now, key, now - 600e3, max]]);
  if (!out[out.length - 1].rows.length) throw new HttpError(429, 'Слишком много запросов, попробуйте позже');
}

const wishView = w => ({ id: w.id, name: w.name, message: w.message, created_at: w.created_at });
const answerView = a => ({ id: a.id, form_id: a.form_id, status: a.status, action: a.action, action_text: a.action_text, fields: JSON.parse(a.fields), created_at: a.created_at });
// уведомить хозяина о новом ответе. Ждём до ответа гостю (не дольше 5 с на всё): на Vercel
// работа после ответа может не завершиться. Ошибка уведомления ответ гостя не портит.
const ICON = { yes: '✅', plus_one: '👫', no: '❌', unknown: '❔' };
async function notifyOwner(invitationId, status, name) {
  if (!AUTH_API) return;
  const deadline = Date.now() + 5000, left = () => Math.max(1, deadline - Date.now());
  try {
    const x = await api(INVITATIONS_API, `/_internal/invitations/${encodeURIComponent(invitationId)}`, { timeout: left() });
    if (!x.user_id) return;
    const text = `${ICON[status]} ${name || 'Гость'} — ${STATUS_RU[status]}
${x.title || 'Приглашение'}`;
    await api(AUTH_API, '/_internal/notify', { method: 'POST', body: { user_id: x.user_id, text }, timeout: left() });
  } catch (e) { console.warn('[guests] уведомление не отправлено:', e.message); }
}

const STATUS_RU = { yes: 'Придёт', plus_one: 'Придёт с парой', no: 'Не придёт', unknown: 'Не указано' };
const csvCell = v => `"${String(v ?? '').replace(/"/g, '""').replace(/^([=+\-@])/, "'$1")}"`;

async function purge(id) {
  await db.batch([['DELETE FROM answers WHERE invitation_id = ?', id], ['DELETE FROM wishes WHERE invitation_id = ?', id]]);
  known.delete(id);
}
// Удалённые приглашения: забираем журнал у invitations сами (раз в минуту, по ходу запросов).
// На Vercel invitations не может вызывать guests — взаимные связи сервисов запрещены; на VPS ещё приходит событие /events.
let syncAt = 0, syncing = null;
function syncDeleted() {
  if (syncing) return syncing;
  if (!INVITATIONS_API || Date.now() - syncAt < 60e3) return Promise.resolve();
  syncAt = Date.now();
  syncing = (async () => {
    const row = await db.get("SELECT value FROM guests_sync WHERE name = 'deleted'");
    const { items } = await api(INVITATIONS_API, `/_internal/deleted?since=${encodeURIComponent(row ? row.value : '')}`, { timeout: 5000 });
    for (const it of items) if (/^[a-z0-9]+$/.test(it.id)) await purge(it.id);
    if (items.length) await db.run("INSERT INTO guests_sync (name, value) VALUES ('deleted', ?) ON CONFLICT (name) DO UPDATE SET value = excluded.value", items[items.length - 1].at);
  })().catch(e => console.warn('[guests] журнал удалений:', e.message)).finally(() => { syncing = null; });
  return syncing;
}

createService('guests', [
  ['POST', '/api/i/:id/rsvp', async (req, res, { params }) => {
    await limit(req, 'rsvp', 40);
    await requirePublished(params.id);
    const b = await readJson(req);
    const fields = Object.fromEntries(Object.entries(b.fields || {}).slice(0, 20).map(([k, v]) => [clip(k, 120), clip(v, 500)]));
    const formId = clip(b.form_id, 40), guestKey = /^[\w-]{8,64}$/.test(b.guest_key || '') ? b.guest_key : null;
    const action = b.action == null ? null : clip(b.action, 60), actionText = b.action_text == null ? null : clip(b.action_text, 200);
    const status = classify(actionText, action, fields);
    // прежний ответ с этого устройства удаляется в той же транзакции. В Postgres перед этим — блокировка
    // по (приглашение, анкета, устройство): иначе два одновременных ответа не видят друг друга и оба остаются
    await db.batch([
      ...guestKey && db.kind === 'pg' ? [['SELECT pg_advisory_xact_lock(hashtext(?))', `guests:${params.id}:${formId}:${guestKey}`]] : [],
      ...guestKey ? [['DELETE FROM answers WHERE invitation_id = ? AND form_id = ? AND guest_key = ?', params.id, formId, guestKey]] : [],
      ['INSERT INTO answers (invitation_id, form_id, action, action_text, fields, created_at, guest_key, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
        params.id, formId, action, actionText, JSON.stringify(fields), new Date().toISOString(), guestKey, status],
    ]);
    const guestName = Object.values(fields).find(v => v && v.length <= 80) || '';
    await notifyOwner(params.id, status, guestName);
    json(res, 200, { ok: true, status });
  }],

  // ответы гостей и сводка — только владельцу
  ['GET', '/api/i/:id/answers', async (req, res, { params }) => {
    await syncDeleted();
    await requireOwner(req, params.id);
    const answers = (await db.all('SELECT * FROM answers WHERE invitation_id = ? ORDER BY id DESC', params.id)).map(answerView);
    json(res, 200, { summary: summary(answers), answers });
  }],

  // то же для Excel: CSV в UTF-8 с BOM
  ['GET', '/api/i/:id/answers.csv', async (req, res, { params }) => {
    await requireOwner(req, params.id);
    const rows = (await db.all('SELECT * FROM answers WHERE invitation_id = ? ORDER BY id', params.id)).map(answerView);
    const lines = [['Когда', 'Ответ', 'Кнопка', 'Данные'].map(csvCell).join(';')];
    for (const a of rows) lines.push([new Date(a.created_at).toLocaleString('ru-RU', { timeZone: 'Asia/Almaty' }), STATUS_RU[a.status], a.action_text || a.action || '',
      Object.entries(a.fields).map(([k, v]) => `${k} ${v}`).join('; ')].map(csvCell).join(';'));
    send(res, 200, 'text/csv; charset=utf-8', '﻿' + lines.join('\r\n'), { 'Content-Disposition': `attachment; filename="answers-${params.id}.csv"` });
  }],

  ['GET', '/api/i/:id/wishes', async (req, res, { params }) => {
    await syncDeleted();
    if (!(await invitation(params.id))) throw new HttpError(404, 'Приглашение не найдено');
    json(res, 200, (await db.all('SELECT * FROM wishes WHERE invitation_id = ? ORDER BY id DESC', params.id)).map(wishView));
  }],

  ['POST', '/api/i/:id/wishes', async (req, res, { params }) => {
    await limit(req, 'wish', 20);
    await requirePublished(params.id);
    const b = await readJson(req);
    const name = clip(b.name, 80), message = clip(b.message, 2000);
    if (!name || !message) throw new HttpError(400, 'Напишите имя и пожелание');
    await db.run('INSERT INTO wishes (invitation_id, name, message, created_at) VALUES (?, ?, ?, ?)', params.id, name, message, new Date().toISOString());
    json(res, 200, { ok: true });
  }],

  // счётчики для «Моих приглашений»: ?ids=a,b,c — только по своим. Список своих берём у сервиса приглашений
  // с cookie вызывающего (без входа — 401), чужие и несуществующие id молча пропускаем.
  // Два запроса с GROUP BY за один заход в базу
  ['GET', '/api/guests/stats', async (req, res, { url }) => {
    await syncDeleted();
    const list = await asCaller(req, '/api/invitations');
    const mine = new Set((Array.isArray(list) ? list : []).map(x => x && x.id));
    const ids = [...new Set((url.searchParams.get('ids') || '').split(',').filter(id => mine.has(id)).slice(0, 500))];
    const out = {};
    if (ids.length) {
      const inList = ids.map(() => '?').join(', ');
      const [a, w] = await db.batch([
        [`SELECT invitation_id, status, COUNT(*) AS n FROM answers WHERE invitation_id IN (${inList}) GROUP BY invitation_id, status`, ...ids],
        [`SELECT invitation_id, COUNT(*) AS n FROM wishes WHERE invitation_id IN (${inList}) GROUP BY invitation_id`, ...ids],
      ]);
      const statuses = {}, wishes = {};
      for (const r of a.rows) statuses[r.invitation_id] = (statuses[r.invitation_id] || []).concat(Array(r.n).fill({ status: r.status }));
      for (const r of w.rows) wishes[r.invitation_id] = r.n;
      for (const id of ids) {
        const rows = statuses[id] || [];
        out[id] = { ...summary(rows), answers: rows.length, wishes: wishes[id] || 0 };
      }
    }
    json(res, 200, out);
  }],

  // события других сервисов
  ['POST', '/events', async (req, res) => {
    const e = await readJson(req);
    if (e.type === 'invitation.deleted' && e.id) await purge(e.id);
    json(res, 200, { ok: true });
  }],
]);
